spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: 'jdbc:mysql://localhost:3308/cosza_store'
    username: root
    password: admin123
server:
  port: 8081
jwt:
  secret:
    key: 4DlZK+CWaJUlBYGEaWBAVdFfZq0jome64pDV3OzUw+E=